### ISSUE TITLE
editorTopOffset 滚动页面闪跳 

### ISSUE THREAD

**Issue by samueljasika** [yiwuyu/vue-weui-ueditor#1]
只能暂时把editorTopOffset 传值为null    但是这样滚动头部就不会置顶了

**Comment by yiwuyu** [comment]
你好，闪跳是不是因为你的工具条初始位置并不是你的editorTopOffset呢？
因为我是从项目中抽离的，所以还有很多需要修改的地方，欢迎提出建议和BUG

**Comment by samueljasika** [comment]
大神求助    项目打包下载下来 改了几个小自定义的地方 怎么打包  vue-weui-ueditor.min.js  和  vue-weui-ueditor.min.css  啊

**Comment by yiwuyu** [comment]
你是想script引入吗
伊吾鱼YwY
在2017年06月28日 17:52，samueljasika 写道： 大神求助    项目打包下载下来 改了几个小自定义的地方 怎么打包  vue-weui-ueditor.min.js  和  vue-weui-ueditor.min.css  啊

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yiwuyu/vue-weui-ueditor","title":"yiwuyu/vue-weui-ueditor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yiwuyu/vue-weui-ueditor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@samueljasika in #1: 大神求助    项目打包下载下来 改了几个小自定义的地方 怎么打包  vue-weui-ueditor.min.js  和  vue-weui-ueditor.min.css  啊"}],"action":{"name":"View Issue","url":"https://github.com/yiwuyu/vue-weui-ueditor/issues/1#issuecomment-311612620"}}}
